# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

c.fonts.monospace = "Hack"
c.scrolling.smooth = True
c.url.default_page = "https://www.google.ca/"
c.url.start_pages = "https://www.google.ca/"
c.url.searchengines = { "DEFAULT" : "https://www.google.ca/search?hl=en&q={}" }

c.fonts.completion.category = "bold 6pt monospace"
c.fonts.completion.entry = "6pt monospace"
c.fonts.debug_console = "6pt monospace"
c.fonts.downloads = "6pt monospace"
c.fonts.hints = "bold 6pt monospace"
c.fonts.keyhint = "8pt monospace"
c.fonts.statusbar = "6pt monospace"
c.fonts.tabs = "6pt monospace"

c.colors.statusbar.normal.bg = "rgba(80,80,80)"

c.zoom.default = 125

c.backend = "webengine"
#c.backend = "webkit"
#c.content.pdfjs = True

