#!/bin/bash

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

export GTK_THEME=Arc-Dark
export TERMINAL="alacritty"
export terminal="alacritty"
#export GDK_SCALE=2
#export GDK_DPI_SCALE=0.85
export GDK_SCALE=1
export GDK_DPI_SCALE=1.7
#xrdb -load ~/.Xresources &
xrdb -merge .Xresources
~/.fehbg &
xrandr --dpi 200
xset r rate 185 30
xinput --set-prop bcm5974 "libinput Disable While Typing Enabled" 0 
xbindkeys
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
#exec ~/bin/scripts/nextcloud-syncd.sh &
exec i3 -c ~/.config/i3/i3.conf
#exec xmonad
#exec startkde

#exec awesome
